# Base URL of the site, the only required config value
base_url = "https://c0di.github.io/zolablog_may"

# Used in RSS by default
title = "My Zola Blog"
description = "A blog powered by Zola and the Apollo theme"

# The default language
default_language = "en"

# Theme name to use
theme = "apollo"

# Generate RSS feed
#generate_feed = true

# When set to "true", the generated HTML files are minified
minify_html = true

# For overriding the default output directory `public`
output_dir = "public"

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom theme variables here
apollo_menu = [
    { name = "Blog", url = "$BASE_URL" },
    { name = "Tags", url = "$BASE_URL/tags" },
    { name = "Archive", url = "$BASE_URL/archive" },
    { name = "About", url = "$BASE_URL/about" },
]

# Enable reading time display
apollo_reading_time = true

# Enable word count
apollo_word_count = true

# Date format used when listing posts (main page, tags, etc)
apollo_date_format = "%e %B %Y"

# Your social handles, displayed in footer
apollo_social = [
    { name = "github", url = "https://github.com/yourusername" },
    { name = "twitter", url = "https://twitter.com/yourusername" },
]
